### ISSUE TITLE
Convert to ES module

### ISSUE THREAD

**Issue by igorskyflyer** [igorskyflyer/npm-vscode-folderpicker#37]
Convert to an ES module for performance gain with tree-shaking.

Requires:
- [x] igorskyflyer/npm-upath#2,
- [x] igorskyflyer/npm-unc-path#3,
- [x] igorskyflyer/npm-is-rootdir#2,
- [x] igorskyflyer/npm-str-is-in#4,
- [x] igorskyflyer/npm-pathexists#1,
- [x] igorskyflyer/npm-recursive-readdir#19,
- [x] igorskyflyer/npm-valid-path#9,
- [x] igorskyflyer/npm-windev#2,
- [x] igorskyflyer/npm-chars-in-string#2,
- [x] igorskyflyer/npm-zep#27

being done first.

**Comment by igorskyflyer** [comment]
Previously referenced issues cannot be resolved until the new release of [Modern Module](https://github.com/igorskyflyer/npm-modern-module).

**Comment by igorskyflyer** [comment]
> Previously referenced issues cannot be resolved until the new release of [Modern Module](https://github.com/igorskyflyer/npm-modern-module).

Stable enough for production. 🎉💃

**Comment by igorskyflyer** [comment]
Due to issues present when using ES modules in Visual Studio Code extension, implement a cross-over solution until the issues are resolved.

**Comment by igorskyflyer** [comment]
> Due to issues present when using ES modules in Visual Studio Code extension, implement a cross-over solution until the issues are resolved.

See microsoft/vscode#130367.

**Comment by igorskyflyer** [comment]
It's not possible to use ES modules in Visual Studio Code extensions, closed until further notice.
